server:
  port: 0
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/book-show-schema?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: BOOK-SHOW-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka